language: go

# before_install
# install - install any dependencies required
install:
    - go get github.com/gohugoio/hugo    # consume time 70.85s

# script - run the build script
script:
    - hugo

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  email: tom.vollerthun@otto.de
  name: TomVollerthun1337
  verbose: true
  keep-history: true
  local-dir: public
  repo: TomVollerthun1337.github.io
  target_branch: master
  on:
    branch: master  # branch contains Hugo generator code

