language: go

# before_install
# install - install any dependencies required
install:
    - go get github.com/gohugoio/hugo    # consume time 70.85s

# script - run the build script
script:
    - hugo

after_success:
- cd public
- git init
- git config user.email "travis@example.com"
- git config user.name "Travis ci"
- git add .
- git commit -m "snapshot $(date '+%m/%d/%y %H:%M')"
- git push --force --quiet "https://${GITHUB_TOKEN}@github.com/TomVollerthun1337/TomVollerthun1337.github.io.git" master:master 2>&1 >/dev/null

